apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-kitty-api
  name: code-kitty-api
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-kitty-api
  strategy: {}
  template:
    metadata:
      labels:
        app: code-kitty-api
    spec:
      containers:
      - image: ghcr.io/codekittyshow/code-kitty-api:latest
        name: code-kitty-api
        resources: {}
        env:
        - name: PORT
          value: "8080"
        - name: DB_USERNAME
          value: "chamod"
        - name: DB_HOST
          value: "codekitty.sacfe.mongodb.net"
        - name: DB_NAME
          value: "CodeKitty"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: db-password
status: {}
